### ISSUE TITLE
Sleep/wake problem

### ISSUE THREAD

**Issue by kinoute** [kinoute/Hack-Dell-Latitude-E6430#2]
my laptop is e6430 atg ( a12 bios)，the cpu model is i3-3120m，sleep can't work well，i have to push the shutdown button still all the time. awful day. couldn't you tell you where i can fix? THX

_Originally posted by @nmynxy in https://github.com/kinoute/Hack-Dell-Latitude-E6430/issues/1#issuecomment-506192571_

**Comment by Tuan9304** [comment]
Hey,

After some patch to the DSDT file from Rehabman guide, I fixed the sleep/wake problem on my laptop. Just download my patched folder, go to **EFI/CLOVER/ACPI** delete old **Patched** folder and replace it. And then edit **config.plist/Acpi/DSDT name** to **DSDT.aml**

Hope it work well on your laptop

**Comment by kinoute** [comment]
@Tuan9304 Can't find your patched folder/DSDT file on your profile, where is it? Cheers

**Comment by Tuan9304** [comment]
Sorry, I have some problems when uploading file. Here is my file: 

[https://drive.google.com/file/d/1UPwoyL0aiOGfFg5VV82HIAfTGZyZOQx2/view](https://drive.google.com/file/d/1UPwoyL0aiOGfFg5VV82HIAfTGZyZOQx2/view)

**Comment by kinoute** [comment]
@Tuan9304 Awesome, it works like a charm. Thank you so much!, I updated the EFI Folder.

Cheers

**Comment by mikenzb** [comment]
Doesn't seem to work on a 1600x900 version, had to use DSDT from #1 which seems to have issues with sleep/wake still, any ideas? 

Tried ur DSDT but wasn't able to boot, reverted and problem was solved, thanks for the AppleALC guide too.

**Comment by Tuan9304** [comment]
Hello @mikenzb,

I am using some patches for the standard screen (1366x768) so it may not work at a higher resolution. I will update the DSDT file for your screen soon.

Edit 2: Try file below

**Comment by kinoute** [comment]
@Tuan9304 I have a problem with your DSDT I think. First, it seems the internal microphone is not recognized anymore. Secondly, after waking up, the output line (for headphones) doesn't work anymore. Speakers still work. Could it be related to `darkwake`? I'm using 8 at the moment.

Thanks.

**Comment by Tuan9304** [comment]
Oh sorry, I forgot to check the sound. Try this new patch:
[https://drive.google.com/file/d/1MWBAX6-joGByVeFPF1rzGIofWqaZ6e17/view](https://drive.google.com/file/d/1MWBAX6-joGByVeFPF1rzGIofWqaZ6e17/view) (low resolution)
[https://drive.google.com/file/d/1wgt0ikti4L4evyojeOcMB_yNzUsAgbfu/view](https://drive.google.com/file/d/1wgt0ikti4L4evyojeOcMB_yNzUsAgbfu/view) (high resolution)

**Comment by kinoute** [comment]
@Tuan9304 Thanks for your effort. I checked again and the headphones jack port still doesn't work after waking up. Speakers do. I will check tomorrow if it has to do with my `darkwake` boot option. I have it set to 8 at the moment, maybe it's related.

**Comment by Tuan9304** [comment]
@kinoute 

I tried to change the `darkwake` to 0.1,2,8,10 and also added **CodecCommander** but it still didn't work. I have no idea right now. I'm not good at editing config file.

*Update new patched folder: Do not fix this problem, but improve some minor bugs and performance: [https://drive.google.com/file/d/1yA-LP3u3CeP8rLDjX9HjtaLd4Z8p6vcM/view](https://drive.google.com/file/d/1yA-LP3u3CeP8rLDjX9HjtaLd4Z8p6vcM/view) (Rename **DSDT name** in **config.plist/ACPI**: 
DSDT-low.aml for 1366x768
DSDT-high.aml for 1600x900 (not tested yet) )

**Comment by mikenzb** [comment]
> Oh sorry, I forgot to check the sound. Try this new patch:
> https://drive.google.com/file/d/1MWBAX6-joGByVeFPF1rzGIofWqaZ6e17/view (low resolution)
> https://drive.google.com/file/d/1wgt0ikti4L4evyojeOcMB_yNzUsAgbfu/view (high resolution)

I had no issue running this patch for my 1600x900, goes into sleep mode and wakes up fine, also no issues with line out/speakers after waking up.

I disabled hibernation before I patched it so maybe that's why I have no issue?

**Comment by Tuan9304** [comment]
@mikenzb Could you upload your EFI folder, pls ?

**Comment by mikenzb** [comment]
@Tuan9304 Here is my [EFI folder](https://www.dropbox.com/s/kfzggf92vp8mmxo/EFI_1600.zip?dl=0)

I got my DSDT from #1 and then replaced it with the above DSDT.AML only that u uploaded, https://drive.google.com/file/d/1wgt0ikti4L4evyojeOcMB_yNzUsAgbfu/view (high resolution)

Still running 10.14.5 btw.

**Comment by kinoute** [comment]
@Tuan9304 Hey, Did you find by any chance a way to fix the line out not working after sleep/waking up? Cheers

**Comment by ehamwey** [comment]
Access denied for all the google drive links above. @Tuan9304 can you make them viewable by link without needing to request access?

**Comment by Horlamedhey** [comment]
Since I applied the fix, the computer continues rebooting after loading on the boot logo screen for a while.
Please help!!!!

**Comment by clemsyn** [comment]
I have fixed the sleep and wake problem on my e6430.  I updated to A23 bios,  edited slice's DSDT,  made changes to his config,  used SSDTPRgen.sh for C and P states,  used AppleALC,  Whatevergreen, Lilu and USBPorts.kext.  I have the 1600x900 screen and i7 3740 with Nvidia 5200m and bluetooth (which is working but seems like Handoff, Airdrop is not supported).  I am not using any darkwake commands :)   I will try to move to Opencore and see how it goes.

[EFIe6430ver2.zip](https://github.com/kinoute/Hack-Dell-Latitude-E6430/files/4629553/EFIe6430ver2.zip)

**Comment by muyi-2021** [comment]
@clemsyn hi dude i use ur efi     firstly thank u !but  one problem i find.  Fn keys can not to change brightness. can u fix it?

**Comment by clemsyn** [comment]
Fn+Insert = brightness upFn+F3 = brightness down
I no longer own the laptop since I upgraded lately.
    On Wednesday, October 28, 2020, 03:15:49 PM CDT, ironcock <notifications@github.com> wrote:  
 
 


@clemsyn hi dude i use ur efi firstly thank u !but one problem i find. Fn keys can not to change brightness. can u fix it?

**Comment by muyi-2021** [comment]
@clemsyn ok thanks anyway.

**Comment by muyi-2021** [comment]
@clemsyn  By the way dude ur efi 10.15.6 work well! only Fn brightness not original.
